# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "runs", :force => true do |t|
    t.column "project",    :string
    t.column "build",      :string
    t.column "started",    :datetime
    t.column "finished",   :datetime
    t.column "status",     :string,   :default => "running"
    t.column "log",        :text
    t.column "revision",   :integer
    t.column "committer",  :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "repository", :string
  end

end
